name: Build image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: image
      REGISTRY: ghcr.io/queil
    steps:

      - name: Clone the repository
        uses: actions/checkout@v3

      - name: "Fix no space left on device"
        run: rm -rf /opt/hostedtoolcache

      # -- first build & push base so it can be reused downstream
     
      - name: base
        id: base
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: latest ${{ github.sha }}
          context: ./src
          containerfiles: |
            ./src/Containerfile

      - name: Log in to the GitHub Container registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push base
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.base.outputs.image }}
          tags: ${{ steps.base.outputs.tags }}
          registry: ${{ env.REGISTRY }}

      # -- build the rest of the variants

      - name: devops
        id: devops
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: devops
          context: ./src
          containerfiles: |
            ./src/devops.Containerfile

      - name: dotnet-all
        id: dotnetall
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: dotnet-all
          context: ./src
          containerfiles: |
            ./src/dotnet-all.Containerfile

      - name: dotnet-7
        id: dotnet7
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: dotnet-7
          context: ./src
          containerfiles: |
            ./src/dotnet-7.Containerfile

      - name: rust
        id: rust
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: rust
          context: ./src
          containerfiles: |
            ./src/rust.Containerfile

      - name: python
        id: python
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: python
          context: ./src
          containerfiles: |
            ./src/python.Containerfile

      - name: Push devops
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.devops.outputs.image }}
          tags: ${{ steps.devops.outputs.tags }}
          registry: ${{ env.REGISTRY }}
          
      - name: Push dotnet-all
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.dotnetall.outputs.image }}
          tags: ${{ steps.dotnetall.outputs.tags }}
          registry: ${{ env.REGISTRY }}

      - name: Push dotnet-7
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.dotnet7.outputs.image }}
          tags: ${{ steps.dotnet7.outputs.tags }}
          registry: ${{ env.REGISTRY }}
          
      - name: Push rust
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.rust.outputs.image }}
          tags: ${{ steps.rust.outputs.tags }}
          registry: ${{ env.REGISTRY }}

      - name: Push python
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.python.outputs.image }}
          tags: ${{ steps.python.outputs.tags }}
          registry: ${{ env.REGISTRY }}
